name: Docker

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: fabiocicerchia/nginx-lua

jobs:
  # Push image to Docker Hub.
  push:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          ./docker-build.sh
          docker images

      - name: Test images
        run: ./test/test.sh

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login  -u ${{ github.actor }} --password-stdin
        if: github.ref == 'master'

      - name: Push images
        run: ./docker-push.sh
        if: github.ref == 'master'